query CurrentUser {
  currentUser {
    id,
    name,
    projects {
      id,
      name,
      members {
        user {
          id,
          name
        },
        permission
      }
    }
  }
}
