mutation NewProject($name: String!, $template: String!) {
  newProject(name: $name, template: $template) {
    id,
    name,
    members {
      user {
        id,
        name
      },
      permission
    }
  }
}
