
query Project ($id: Int!) {
  project (id: $id) {
    id,
    name,
    members {
      user {
        id,
        name
      },
      permission
    },
    files {
      name,
      path,
      extension,
      children {
        name,
        path,
        extension,
        children {
          name,
          path,
          extension,
          children {
            name,
            path,
            extension,
            children {
              name,
              path,
              extension,
              isDir
            },
            isDir
          },
          isDir
        },
        isDir
      },
      isDir
    }
  }
}
